version: "3.7"
services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: superset
      POSTGRES_USER: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8096:8080
  superset:
    image: amancevice/superset
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - 8200:8088
    volumes:
      - ./conf:/etc/superset
  celery_worker:
    image: amancevice/superset
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./conf:/etc/superset
      - ./data:/var/lib/superset
    command: celery worker --app=superset.tasks.celery_app:app --pool=prefork -O fair -c 4
  celery_beat:
    image: amancevice/superset
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./conf:/etc/superset
      - ./data:/var/lib/superset
    command: celery beat --app=superset.tasks.celery_app:app
  celery_flower:
    image: amancevice/superset
    restart: unless-stopped
    depends_on:
      - redis
    ports:
      - 5555:5555
    volumes:
      - ./conf:/etc/superset
      - ./data:/var/lib/superset
    command: celery flower --app=superset.tasks.celery_app:app
volumes:
  redis:

